# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6.8


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/


before_script:
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt

test:
  
  script:
      - pytest test_spellchecker.py
      
